name: Release Tools

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build Binaries
        run: |
          mkdir dist

          GOOS=linux GOARCH=amd64 go build -o dist/checker-linux-amd64 ./cmd/checker
          GOOS=linux GOARCH=amd64 go build -o dist/unique-linux-amd64 ./cmd/unique
          GOOS=linux GOARCH=amd64 go build -o dist/updater-linux-amd64 ./cmd/updater

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
